### PR TITLE
Dirty fix for MangaFox.me + remove exception in BSync.js

### PR DESCRIPTION
**Pull request by Alidou**
This change is [Reviewable](https://reviewable.io/reviews/allmangasreader-dev/amr/148)

### CODE REVIEW

**Comment by braiam** [comment]
Can you separate this pull request in two. I see no "fix" for mangafox.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/allmangasreader-dev/amr/148#-:-KjPqiUSRdJhUcuFRhvs:b1sboas)*

**Comment by haidbz** [comment]
I haven't actually checked out the code, but it didn't help with MangaFox at all for me.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/allmangasreader-dev/amr/148#-:-KlJJ_4e6oAiMn-MSpwr:bopjveg)*

**Comment by Alidou** [comment]
Sorry, I was busy and forgot about this. 
My "fix" for MangaFox was in js/back.js.
I changed the timeout for loading the pictures once it failed. 
I put 500 miliseconds. The previous value, 100, was too much on my side and mangafox was rejecting the request. 
IMO, It would be better in the future to : 
1) Allow the retry when clicking on the picture (I saw that feature before but it is not in the current version of develop)
2) Have that value as a setting. Either a setting of the manga website, and or a global setting of the extension.

**Comment by DakuTree** [comment]
Even 500ms is still too low, best to go for 1000ms as that seems to be what their limit is (1 request per/s).

A better solution here is to just use the mobile site to grab the images, as that doesn't have the same request per/s limitations so all pages can be loaded instantly.  
The only issue I've noticed with this is that it won't work for certain series (particularly licensed series). MangaFox seems to block access to series by region on the desktop viewer, but the mobile viewer seems to block access regardless of region. Can just fallback to the old method in these cases.

**Comment by haidbz** [comment]
I've been mucking around with the code while using the Chrome dev tools, and it appears the timeout isn't the real problem. I have currently set the timeout to 2ms, and it works sometimes, albeit even slower than when set to 1000 ms.

It seems to stop, however, as soon as one of the pages return http status code 503 rather than 200. If we could catch that and send a new request for the page when it happens, that might be a better fix. Unfortunately, I am too inexperienced with JS and haven't figured out how that might be done.

**Comment by braiam** [comment]
I'm going to reject this PR, as it doesn't solve the issue with MangaFox and there is a mechanism that would allow people to gracefully retry loading the image. I would be willing to accept a PR that fixes the retry logic on the extension.

**Pull request closed without merging**
